version: '3.3'
services:
  patientsdb:
    build:
      dockerfile: ./docker/db.dockerfile
      context: .
    image: evisita/patientsdb
    container_name: evisita-patientsdb
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=patientsdb
    networks:
      - evisita-network
  oapi-srv-patients:
    build:
      dockerfile: ./docker/srv.dockerfile
      context: .
    image: evisita/oapi-srv-patients
    container_name: evisita-oapisrvpatients
    ports:
      - '8083:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - evisita-network
    depends_on:
      - patientsdb

networks:
  evisita-network:
    driver: bridge