version: '3.3'
services:
  database:
    build : ./database
    container_name: 'pacientesdb'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pacientesdb
#  app:
#    build: ./app
#    container_name: api_nodejs
#    ports:
#      - '5000:5000'
#    depends_on:
#      - db